#!/bin/sh

# MIT license (c) 2024 https://github.com/slowpeek
# Homepage: https://github.com/slowpeek/mc-iso9660xl
# About: Readonly xorriso based ISO9660 plugin for Midnight Commander

bye() {
    printf '%s\n' "$1" >&2
    exit 1
}

# This snippet is used to undo xorriso's Text_shellsafe(). Pseudocode for the
# function:
#
# Text_shellsafe( s) {
#     return q(') replace(q('), q('"'"'), s) q(')
# }
#
# Xorriso_ls() uses two formats for pathes:
# - generic: Text_shellsafe(path)
# - symlink: Text_shellsafe(link) q( -> ) Text_shellsafe(target)
#
# References in xorriso sources:
# - iso_tree.c:Xorriso_ls()
# - text_io.c:Xorriso_esc_filepath()
# - misc_funct.c:Text_shellsafe()
awk_xorriso_unesc=$(cat <<'EOF'
{
    # Start of the path part
    i = index($0, "'")

    s = substr($0, i)
    # The path part with the wrapping quotes removed
    s = substr(s, 2, length(s)-2)

    if (substr($0, 1, 1) == "l") {
        s1=s
        if (gsub("->", "", s1) > 1) {
            # Ambiguity: either the link or its target contains q(->) in
            # addition to the link/target delimiter
            next
        }

        j = index(s, "' -> '")
        # link -> target with the wrapping quotes removed from both
        s = substr(s, 1, j-1) " -> " substr(s, j+6)
    } else if (index(s, "->")) {
        # Ambiguity: not a symlink, but there is q(->)
        next
    }

    gsub("'\"'\"'", "'", s)
    print substr($0, 1, i-1) s
}
EOF
)

command -v xorriso >/dev/null ||
    bye 'xorriso is not installed'

cmd=$1
shift

case "$cmd" in
    list)
        temp_ls=$(mktemp "${MC_TMPDIR:-/tmp}"/mc-iso9660xl.XXXXXX) || exit
        # shellcheck disable=SC2064
        trap "rm -f '${temp_ls}'" EXIT

        xorriso -dev stdio:"$1" -find / -exec lsdl 2>/dev/null > "$temp_ls" || exit

        # The first line is /, skip it
        tail -n+2 "$temp_ls" |
            # disk_ops.c:Xorriso_format_ls_l() prints the boot catalog file as
            # of type "e". Make it a generic file
            sed -E 's,^e,-,' |
            awk "$awk_xorriso_unesc"

        exit ;;

    copyout)
        xorriso -dev stdio:"$1" -osirrox on -extract "$2" "$3" >/dev/null
        exit ;;

    *)
        exit 1 ;;
esac
