#!/bin/sh
# shellcheck disable=SC3043

# MIT license (c) 2024 https://github.com/slowpeek
# Homepage: https://github.com/slowpeek/mc-iso9660xl
# About: Readonly xorriso based ISO9660 plugin for Midnight Commander

bye() {
    printf '%s\n' "$1" >&2
    exit 1
}

# This snippet is used to undo xorriso's Text_shellsafe(). Pseudocode for the
# function:
#
# Text_shellsafe( s) {
#     return q(') replace(q('), q('"'"'), s) q(')
# }
#
# Xorriso_ls() uses two formats for pathes:
# - generic: Text_shellsafe(path)
# - symlink: Text_shellsafe(link) q( -> ) Text_shellsafe(target)
#
# References in xorriso sources:
# - iso_tree.c:Xorriso_ls()
# - text_io.c:Xorriso_esc_filepath()
# - misc_funct.c:Text_shellsafe()
awk_xorriso_unesc=$(cat <<'EOF'
{
    # Start of the path part
    i = index($0, "'")

    s = substr($0, i)
    # The path part with the wrapping quotes removed
    s = substr(s, 2, length(s)-2)

    if (substr($0, 1, 1) == "l") {
        s1=s
        if (gsub("->", "", s1) > 1) {
            # Ambiguity: either the link or its target contains q(->) in
            # addition to the link/target delimiter
            next
        }

        j = index(s, "' -> '")
        # link -> target with the wrapping quotes removed from both
        s = substr(s, 1, j-1) " -> " substr(s, j+6)
    } else if (index(s, "->")) {
        # Ambiguity: not a symlink, but there is q(->)
        next
    }

    gsub("'\"'\"'", "'", s)
    print substr($0, 1, i-1) s
}
EOF
)

run_xorriso() {
    local iso="$1"
    shift

    xorriso -report_about WARNING -dev stdio:"$iso" "$@"
    local _st=$?

    # Append "x" to protect any trailing empty lines from trimming by
    # log=$(run_xorriso ..). The empty line of interest is the one produced by
    # xorriso_main.c:yell_xorriso() when the header is the only content in
    # stderr. The sed command in process_log() cant remove the header if the
    # empty line is not there
    echo x >&2
    return "$_st"
}

process_log() {
    # Remove the header produced by xorriso_main.c:yell_xorriso()
    log=$(printf '%s' "$log" | sed -E '1{/xorriso .+ filesystem manipulator/{N;d;};}')

    # If there is anything left, pass it to mc (with the "x" protector removed)
    [ "$log" = x ] || printf -- '%s' "$log" | head -n-1 | fmt -sw 70 >&2
}

command -v xorriso >/dev/null ||
    bye 'xorriso is not installed'

cmd=$1
shift

case "$cmd" in
    list)
        temp_ls=$(mktemp "${MC_TMPDIR:-/tmp}"/mc-iso9660xl.XXXXXX) || exit
        # shellcheck disable=SC2064
        trap "rm -f '${temp_ls}'" EXIT

        log=$(run_xorriso "$1" -find / -exec lsdl 2>&1 >"$temp_ls")
        _st=$?

        process_log
        [ "$_st" = 0 ] || exit "$_st"

        # The first line is /, skip it
        tail -n+2 "$temp_ls" |
            # disk_ops.c:Xorriso_format_ls_l() prints the boot catalog file as
            # of type "e". Make it a generic file
            sed -E 's,^e,-,' |
            awk "$awk_xorriso_unesc"

        exit ;;

    copyout)
        log=$(run_xorriso "$1" -osirrox on -extract "$2" "$3" 2>&1 >/dev/null)
        _st=$?

        process_log
        exit "$_st" ;;

    *)
        exit 1 ;;
esac
